# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Alliases',
                'verbose_name_plural': 'Alliases',
            },
        ),
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_email', models.CharField(blank=True, max_length=50, null=True)),
                ('id_fw', models.CharField(blank=True, max_length=50, null=True)),
                ('forward', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yes/No')),
                ('copy', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yes/No')),
                ('filter_param', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forwarding to')),
            ],
            options={
                'verbose_name': 'Forward',
                'verbose_name_plural': 'Forward',
            },
        ),
        migrations.CreateModel(
            name='InfoEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=50, null=True)),
                ('iname', models.CharField(blank=True, max_length=50, null=True)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('uid', models.CharField(max_length=50)),
                ('enabled', models.CharField(blank=True, max_length=50, null=True)),
                ('ready', models.CharField(blank=True, max_length=50, null=True)),
                ('hintq', models.CharField(max_length=50, verbose_name='Secret Question')),
            ],
            options={
                'verbose_name': 'Info Email',
                'verbose_name_plural': 'Info Email',
            },
        ),
        migrations.CreateModel(
            name='MailAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Домен')),
                ('token1', models.CharField(max_length=250, verbose_name='API_v1 Token')),
                ('token2', models.CharField(max_length=250, verbose_name='API_v2 Token')),
                ('default_email_forward', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Почта для переадресации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail Admin',
                'verbose_name_plural': 'Mail Admin',
            },
        ),
        migrations.CreateModel(
            name='Maillist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('infoemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex.InfoEmail')),
            ],
            options={
                'verbose_name': 'Maillist',
                'verbose_name_plural': 'Maillist',
            },
        ),
        migrations.AddField(
            model_name='infoemail',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex.MailAdmin'),
        ),
        migrations.AddField(
            model_name='alliases',
            name='info_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex.InfoEmail'),
        ),
    ]
